// <auto-generated />
using AptWatchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AptWatchApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709163332_ThemBangSanPham")]
    partial class ThemBangSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AptWatchApi.Models.LangNghe", b =>
                {
                    b.Property<int>("MaLangNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLangNghe"));

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<string>("TenLangNghe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("MaLangNghe");

                    b.ToTable("LangNghe");
                });
#pragma warning restore 612, 618
        }
    }
}
