// <auto-generated />
using AptWatchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AptWatchApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709171221_TaoBangSanPham")]
    partial class TaoBangSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AptWatchApi.Models.LangNghe", b =>
                {
                    b.Property<int>("MaLangNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLangNghe"));

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<string>("TenLangNghe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("MaLangNghe");

                    b.ToTable("LangNghe");
                });

            modelBuilder.Entity("AptWatchApi.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaLangNghe");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("AptWatchApi.Models.SanPham", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany()
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LangNghe");
                });
#pragma warning restore 612, 618
        }
    }
}
