// <auto-generated />
using System;
using AptWatchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AptWatchApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AptWatchApi.Models.DanhGiaLangNghe", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("AnhDinhKam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SoSao")
                        .HasColumnType("tinyint");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaLangNghe");

                    b.ToTable("DanhGiaLangNghe", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.LangNghe", b =>
                {
                    b.Property<int>("MaLangNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLangNghe"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DanhSachAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiemDanhGia")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("DuongDanSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiThieuNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("KinhDo")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<string>("LichSuHinhThanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaNhomNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaQuanLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuotDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("TenLangNghe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ViDo")
                        .HasColumnType("decimal(10, 8)");

                    b.HasKey("MaLangNghe");

                    b.HasIndex("MaNhomNghe");

                    b.ToTable("LangNghe", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.NgheNhan", b =>
                {
                    b.Property<int>("MaNgheNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgheNhan"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DanhHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("SoTruong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNgheNhan");

                    b.HasIndex("MaLangNghe");

                    b.ToTable("NgheNhan", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.NhomNghe", b =>
                {
                    b.Property<int>("MaNhomNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomNghe"));

                    b.Property<string>("IconMinhHoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaMauTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhomNghe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhomNghe");

                    b.ToTable("NhomNghe", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("DanhSachAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDanSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNgheNhan")
                        .HasColumnType("int");

                    b.Property<bool>("SanPhamtieuBieu")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaLangNghe");

                    b.HasIndex("MaNgheNhan");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.ThuyetMinhAudio", b =>
                {
                    b.Property<int>("MaThuyetMinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuyetMinh"));

                    b.Property<string>("DuongDanAudio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<string>("MaNgonNgu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoiDungVaniBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuongGiay")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThuyetMinh");

                    b.HasIndex("MaLangNghe");

                    b.ToTable("ThuyetMinhAudio", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.TourTraiNghiem", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LichTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLangNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNgheNhan")
                        .HasColumnType("int");

                    b.Property<int>("SoKhachToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ThoiGianGio")
                        .HasColumnType("decimal(4, 1)");

                    b.HasKey("MaTour");

                    b.HasIndex("MaLangNghe");

                    b.HasIndex("MaNgheNhan");

                    b.ToTable("TourTraiNghiem", (string)null);
                });

            modelBuilder.Entity("AptWatchApi.Models.DanhGiaLangNghe", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany("DanhSachDanhGia")
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LangNghe");
                });

            modelBuilder.Entity("AptWatchApi.Models.LangNghe", b =>
                {
                    b.HasOne("AptWatchApi.Models.NhomNghe", "NhomNghe")
                        .WithMany("DanhSachLangNghe")
                        .HasForeignKey("MaNhomNghe")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhomNghe");
                });

            modelBuilder.Entity("AptWatchApi.Models.NgheNhan", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany("DanhSachNgheNhan")
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LangNghe");
                });

            modelBuilder.Entity("AptWatchApi.Models.SanPham", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AptWatchApi.Models.NgheNhan", "NgheNhan")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("MaNgheNhan");

                    b.Navigation("LangNghe");

                    b.Navigation("NgheNhan");
                });

            modelBuilder.Entity("AptWatchApi.Models.ThuyetMinhAudio", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany("DanhSachAudio")
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LangNghe");
                });

            modelBuilder.Entity("AptWatchApi.Models.TourTraiNghiem", b =>
                {
                    b.HasOne("AptWatchApi.Models.LangNghe", "LangNghe")
                        .WithMany("DanhSachTour")
                        .HasForeignKey("MaLangNghe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AptWatchApi.Models.NgheNhan", "NgheNhan")
                        .WithMany()
                        .HasForeignKey("MaNgheNhan");

                    b.Navigation("LangNghe");

                    b.Navigation("NgheNhan");
                });

            modelBuilder.Entity("AptWatchApi.Models.LangNghe", b =>
                {
                    b.Navigation("DanhSachAudio");

                    b.Navigation("DanhSachDanhGia");

                    b.Navigation("DanhSachNgheNhan");

                    b.Navigation("DanhSachSanPham");

                    b.Navigation("DanhSachTour");
                });

            modelBuilder.Entity("AptWatchApi.Models.NgheNhan", b =>
                {
                    b.Navigation("DanhSachSanPham");
                });

            modelBuilder.Entity("AptWatchApi.Models.NhomNghe", b =>
                {
                    b.Navigation("DanhSachLangNghe");
                });
#pragma warning restore 612, 618
        }
    }
}
